version: "3"

networks:
  traefik-proxy:

services:
  ######################################################################################################################
  # Traefik
  ######################################################################################################################
  traefik:
    image: traefik
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:9000"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--experimental.localPlugins.redirect.moduleName=github.com/supergoudvis116/regex-redirect-joule"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".:/plugins-local/src/github.com/supergoudvis116/regex-redirect-joule"
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    networks:
      - traefik-proxy

  ######################################################################################################################
  # Traefik
  ######################################################################################################################
  whoami:
    image: traefik/whoami
    networks:
      - traefik-proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=redirect"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[0].regex=/301$$"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[0].replacement=/moved-permanently"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[0].statusCode=301"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[1].regex=/302$$"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[1].replacement=/found"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[1].statusCode=302"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[2].regex=/307$$"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[2].replacement=/temporary-redirect"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[2].statusCode=307"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[3].regex=/308$$"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[3].replacement=/permanent-redirect"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[3].statusCode=308"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[4].regex=/404$$"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[4].statusCode=404"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[5].regex=/410$$"
      - "traefik.http.middlewares.redirect.plugin.redirect.redirects[5].statusCode=410"
